// Auto-generated posts snippet
{
  "id": "organic-auto-mid1-urban-3mg87j-20260217_021604",
  "status": "new",
  "category": "mid1",
  "department": "化學系",
  "subject": "有機化學",
  "title": "【期中一】有機化學 2014-2024（Urban）",
  "tags": [
    "有機化學",
    "期中一",
    "自動匯入"
  ],
  "author": "Urban",
  "replies": 0,
  "views": 0,
  "createdAt": "2026-02-17",
  "lastReplyAt": "2026-02-17 00:00",
  "lastReplyBy": "Urban",
  "attachments": [
    "./assets/organic_chemistry/113organic/mid1.pdf",
    "./assets/organic_chemistry/112organic/mid_1/exam1-1.jpg",
    "./assets/organic_chemistry/112organic/mid_1/exam1-2.jpg",
    "./assets/organic_chemistry/112organic/mid_1/exam1-3.jpg",
    "./assets/organic_chemistry/112organic/mid_1/mid_1_merged.pdf",
    "./assets/organic_chemistry/112organic/mid1/1.jpg",
    "./assets/organic_chemistry/112organic/mid1/2.jpg",
    "./assets/organic_chemistry/112organic/mid1/3.jpg",
    "./assets/organic_chemistry/112organic/mid1/4.jpg",
    "./assets/organic_chemistry/112organic/mid1/5.jpg",
    "./assets/organic_chemistry/112organic/mid1/6.jpg",
    "./assets/organic_chemistry/112organic/mid1/7.jpg",
    "./assets/organic_chemistry/112organic/mid1/8.jpg",
    "./assets/organic_chemistry/112organic/mid1/9.jpg",
    "./assets/organic_chemistry/112organic/mid1/mid1_merged.pdf",
    "./assets/organic_chemistry/111organic/111/organic_first_exam.pdf",
    "./assets/organic_chemistry/111organic/organic_first_term_exam.pdf",
    "./assets/organic_chemistry/109organic/mid_1/20210409organicfirst_mid.pdf",
    "./assets/organic_chemistry/110organic/mid1/organic_mid_1.pdf",
    "./assets/organic_chemistry/109organic/item/109_first_mid.pdf",
    "./assets/organic_chemistry/109organic/mid_1/organic_mid_1.pdf",
    "./assets/organic_chemistry/106organic_chemistry/106organicmid1.doc",
    "./assets/organic_chemistry/103organic/103organic_first_mid/1.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/103organic_first_mid_merged.pdf",
    "./assets/organic_chemistry/103organic/103organic_first_mid/2.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/3.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/4.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/5.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/6.jpg",
    "./assets/organic_chemistry/103organic/103organic_first_mid/7.jpg",
    "./assets/organic_chemistry/item/10720_mid1.pdf",
    "./assets/organic_chemistry/item/10820_mid1.pdf"
  ]
},
{
  "id": "organic-auto-mid2-urban-3mg87j-20260217_021604",
  "status": "new",
  "category": "mid2",
  "department": "化學系",
  "subject": "有機化學",
  "title": "【期中二】有機化學 2014-2024（Urban）",
  "tags": [
    "有機化學",
    "期中二",
    "自動匯入"
  ],
  "author": "Urban",
  "replies": 0,
  "views": 0,
  "createdAt": "2026-02-17",
  "lastReplyAt": "2026-02-17 00:00",
  "lastReplyBy": "Urban",
  "attachments": [
    "./assets/organic_chemistry/113organic/mid2_answers.pdf",
    "./assets/organic_chemistry/113organic/mid2.pdf",
    "./assets/organic_chemistry/112organic/mid_2/exam2-1.jpg",
    "./assets/organic_chemistry/112organic/mid_2/exam2-2.jpg",
    "./assets/organic_chemistry/112organic/mid_2/exam2-3.jpg",
    "./assets/organic_chemistry/112organic/mid_2/mid_2_merged.pdf",
    "./assets/organic_chemistry/112organic/mid2/1.jpg",
    "./assets/organic_chemistry/112organic/mid2/10.jpg",
    "./assets/organic_chemistry/112organic/mid2/2.jpg",
    "./assets/organic_chemistry/112organic/mid2/3.jpg",
    "./assets/organic_chemistry/112organic/mid2/4.jpg",
    "./assets/organic_chemistry/112organic/mid2/5.jpg",
    "./assets/organic_chemistry/112organic/mid2/6.jpg",
    "./assets/organic_chemistry/112organic/mid2/7.jpg",
    "./assets/organic_chemistry/112organic/mid2/8.jpg",
    "./assets/organic_chemistry/112organic/mid2/9.jpg",
    "./assets/organic_chemistry/112organic/mid2/mid2_merged.pdf",
    "./assets/organic_chemistry/111organic/111/ans/ans_for_second_exam.pdf",
    "./assets/organic_chemistry/111organic/111/organic_second_exam.pdf",
    "./assets/organic_chemistry/111organic/answers_to_second_term.pdf",
    "./assets/organic_chemistry/111organic/organic_second_term_exam.pdf",
    "./assets/organic_chemistry/109organic/mid_2/20210504organicsecond_mid.pdf",
    "./assets/organic_chemistry/109organic/item/109_second_mid.pdf",
    "./assets/organic_chemistry/109organic/mid_2/organic_mid_2.pdf",
    "./assets/organic_chemistry/107organic/midsecond/img_6943.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6944.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6945.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6946.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6947.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6948.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6949.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6950.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6951.jpg",
    "./assets/organic_chemistry/107organic/midsecond/img_6952.jpg",
    "./assets/organic_chemistry/107organic/midsecond/midsecond_merged.pdf",
    "./assets/organic_chemistry/106organic_chemistry/106organicmid2.doc",
    "./assets/organic_chemistry/103organic/103organic_second_mid/1.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/10.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/103organic_second_mid_merged.pdf",
    "./assets/organic_chemistry/103organic/103organic_second_mid/11.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/2.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/3.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/4.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/5.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/6.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/7.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/8.jpg",
    "./assets/organic_chemistry/103organic/103organic_second_mid/9.jpg"
  ]
},
{
  "id": "organic-auto-final-urban-3mg87j-20260217_021604",
  "status": "new",
  "category": "final",
  "department": "化學系",
  "subject": "有機化學",
  "title": "【期末】有機化學 2017-2024（Urban）",
  "tags": [
    "有機化學",
    "期末",
    "自動匯入"
  ],
  "author": "Urban",
  "replies": 0,
  "views": 0,
  "createdAt": "2026-02-17",
  "lastReplyAt": "2026-02-17 00:00",
  "lastReplyBy": "Urban",
  "attachments": [
    "./assets/organic_chemistry/113organic/final.pdf",
    "./assets/organic_chemistry/112organic/final/1_2.jpg",
    "./assets/organic_chemistry/112organic/final/1.jpg",
    "./assets/organic_chemistry/112organic/final/112final_analysis.pdf",
    "./assets/organic_chemistry/112organic/final/112finalanswers_2.pdf",
    "./assets/organic_chemistry/112organic/final/112finalanswers.pdf",
    "./assets/organic_chemistry/112organic/final/2_2.jpg",
    "./assets/organic_chemistry/112organic/final/2.jpg",
    "./assets/organic_chemistry/112organic/final/3_2.jpg",
    "./assets/organic_chemistry/112organic/final/3.jpg",
    "./assets/organic_chemistry/112organic/final/4.jpg",
    "./assets/organic_chemistry/112organic/final/5.jpg",
    "./assets/organic_chemistry/112organic/final/6.jpg",
    "./assets/organic_chemistry/112organic/final/7.jpg",
    "./assets/organic_chemistry/112organic/final/8.jpg",
    "./assets/organic_chemistry/112organic/final/9.jpg",
    "./assets/organic_chemistry/112organic/final/finalanswers.pdf",
    "./assets/organic_chemistry/108organic/final/20220214_233848.jpg",
    "./assets/organic_chemistry/108organic/final/20220214_233902.jpg",
    "./assets/organic_chemistry/108organic/final/20220214_233913.jpg",
    "./assets/organic_chemistry/108organic/final/20220214_233925.jpg",
    "./assets/organic_chemistry/110organic/final/organic_chemistry-ii-online-exam--fixed.pdf",
    "./assets/organic_chemistry/109organic/final/109_final.pdf",
    "./assets/organic_chemistry/109organic/final/img_6869.jpg",
    "./assets/organic_chemistry/109organic/final/img_6870.jpg",
    "./assets/organic_chemistry/109organic/final/img_6871.jpg",
    "./assets/organic_chemistry/108organic/final/final_merged.pdf",
    "./assets/organic_chemistry/108organic/final/img_6874.jpg",
    "./assets/organic_chemistry/108organic/final/img_6875.jpg",
    "./assets/organic_chemistry/108organic/final/img_6876.jpg",
    "./assets/organic_chemistry/108organic/final/img_6877.jpg",
    "./assets/organic_chemistry/108organic/final/img_6878.jpg",
    "./assets/organic_chemistry/108organic/final/img_6879.jpg",
    "./assets/organic_chemistry/108organic/final/img_6880.jpg",
    "./assets/organic_chemistry/108organic/final/img_6881.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/final_merged.pdf",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6931.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6932.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6933.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6934.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6935.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6936.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6937.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6938.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6939.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6940.jpg",
    "./assets/organic_chemistry/106organic_chemistry/final/img_6941.jpg"
  ]
}
