// 你之後就一直往這個陣列加資料就好。
// attachment 可指向：
// 1) PDF：  ./化學系必修/普通化學/xxx.pdf
// 2) 其他檔案
// 也支援 attachments: ["./a.pdf","./b.pdf"]（同一篇多檔）
// ⚠️ 若路徑包含中文或空格，請使用 encodeURI()

window.POSTS = [
    {
        id: "calculator-stat-tutorial-2026",
        status: "new",
        category: "notes",
        department: "通識課",
        subject: "計算機統計",
        title: "【教學】計算機統計功能教學（平均值 / 標準差 / 線性回歸）",
        tags: ["教學", "計算機", "統計"],
        author: "allen",
        replies: 0,
        views: 120,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-16 20:10",
        lastReplyBy: "allen",
        attachment: "./assets/calculate_pratice/calculator_statistics_practice.pdf"
    },
    {
        id: "analytical-chem-1-first-archive",
        status: "new",
        category: "mid1",
        department: "化學系",
        subject: "分析化學一",
        title: "【期中一】分析化學一 first 歷年題庫整理（陳貴通）",
        tags: ["分析化學一", "first", "歷年"],
        author: "陳貴通",
        replies: 0,
        views: 60,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-16 20:35",
        lastReplyBy: "陳貴通",
        attachments: [
            "./assets/analytical_chem/analytical1/first/2024_first_midterm_exam_solutions.pdf",
            "./assets/analytical_chem/analytical1/first/2023_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2021_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2020_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2019_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2017_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2016_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/first/2018_analytical_chem_1.pdf"
        ]
    },
    {
        id: "analytical-chem-1-second-archive",
        status: "new",
        category: "mid2",
        department: "化學系",
        subject: "分析化學一",
        title: "【期中二】分析化學一 second 歷年題庫整理（陳貴通）",
        tags: ["分析化學一", "second", "歷年"],
        author: "陳貴通",
        replies: 0,
        views: 42,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-17 09:30",
        lastReplyBy: "陳貴通",
        attachments: [
            "./assets/analytical_chem/analytical1/second/2024_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2023_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2022_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2021_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2020_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2019_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2018_second_midterm_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/second/2017_second_midterm_analytical_chem_1.pdf"
        ]
    },
    {
        id: "analytical-chem-1-final-archive",
        status: "new",
        category: "final",
        department: "化學系",
        subject: "分析化學一",
        title: "【期末】分析化學一 final 歷年題庫整理（陳貴通）",
        tags: ["分析化學一", "final", "歷年"],
        author: "陳貴通",
        replies: 0,
        views: 40,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-17 09:35",
        lastReplyBy: "陳貴通",
        attachments: [
            "./assets/analytical_chem/analytical1/final/2024_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2023_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2021_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2020_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2019_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2018_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2017_final_analytical_chem_1.pdf",
            "./assets/analytical_chem/analytical1/final/2016_final_analytical_chem_1.pdf"
        ]
    },
    {
        id: "analytical-chem-2-mid1-archive",
        status: "new",
        category: "mid1",
        department: "化學系",
        subject: "分析化學二",
        title: "【期中一】分析化學二 mid1 歷年題庫整理（Urban）",
        tags: ["分析化學二", "mid1", "歷年"],
        author: "Urban",
        replies: 0,
        views: 20,
        createdAt: "2026-02-17",
        lastReplyAt: "2026-02-17 11:20",
        lastReplyBy: "Urban",
        attachments: [
            "./assets/analytical_chem/analytical2/mid1/113-midterm1.pdf",
            "./assets/analytical_chem/analytical2/mid1/112-midterm1.pdf",
            "./assets/analytical_chem/analytical2/mid1/111-midterm1.pdf",
            "./assets/analytical_chem/analytical2/mid1/110-midterm1.pdf",
            "./assets/analytical_chem/analytical2/mid1/109-midterm1.pdf",
            "./assets/analytical_chem/analytical2/mid1/108-midterm1.pdf"
        ]
    },
    {
        id: "analytical-chem-2-mid2-archive",
        status: "new",
        category: "mid2",
        department: "化學系",
        subject: "分析化學二",
        title: "【期中二】分析化學二 mid2 歷年題庫整理（Urban）",
        tags: ["分析化學二", "mid2", "歷年"],
        author: "Urban",
        replies: 0,
        views: 20,
        createdAt: "2026-02-17",
        lastReplyAt: "2026-02-17 11:22",
        lastReplyBy: "Urban",
        attachments: [
            "./assets/analytical_chem/analytical2/mid2/113-midterm2.pdf",
            "./assets/analytical_chem/analytical2/mid2/112-midterm2.pdf",
            "./assets/analytical_chem/analytical2/mid2/111-midterm2.pdf",
            "./assets/analytical_chem/analytical2/mid2/110-midterm2.pdf",
            "./assets/analytical_chem/analytical2/mid2/109-midterm2.pdf",
            "./assets/analytical_chem/analytical2/mid2/108-midterm2.pdf"
        ]
    },
    {
        id: "analytical-chem-2-final-archive",
        status: "new",
        category: "final",
        department: "化學系",
        subject: "分析化學二",
        title: "【期末】分析化學二 final 歷年題庫整理（Urban）",
        tags: ["分析化學二", "final", "歷年"],
        author: "Urban",
        replies: 0,
        views: 18,
        createdAt: "2026-02-17",
        lastReplyAt: "2026-02-17 11:24",
        lastReplyBy: "Urban",
        attachments: [
            "./assets/analytical_chem/analytical2/final/113-final.pdf",
            "./assets/analytical_chem/analytical2/final/112-final.pdf",
            "./assets/analytical_chem/analytical2/final/111-final.pdf",
            "./assets/analytical_chem/analytical2/final/110-final.pdf",
            "./assets/analytical_chem/analytical2/final/108-final.pdf"
        ]
    },
    {
        id: "analytical-chem-2-assistant-materials",
        status: "new",
        category: "mid2",
        department: "化學系",
        subject: "分析化學二",
        title: "【期中二】分析化學二助教教材整理（Urban）",
        tags: ["分析化學二", "助教教材", "assistant"],
        author: "Urban",
        replies: 0,
        views: 30,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-16 21:15",
        lastReplyBy: "Urban",
        attachments: [
            "./assets/analytical_chem/analytical2/assistant/l15_l16_20210506.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch10_20210408.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch5_9_20210325.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch2_3_20210311.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch1_20210304.pdf",
            "./assets/analytical_chem/analytical2/assistant/chapter_28.pdf",
            "./assets/analytical_chem/analytical2/assistant/chapter_26_27.pdf",
            "./assets/analytical_chem/analytical2/assistant/chapter_20_26.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch15_1.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch13_15.pdf",
            "./assets/analytical_chem/analytical2/assistant/ch4_1.pdf",
            "./assets/analytical_chem/analytical2/assistant/l9.pdf"
        ]
    },
    {
        id: "analytical-chem-2-quiz-archive",
        status: "new",
        category: "mid2",
        department: "化學系",
        subject: "分析化學二",
        title: "【期中二】分析化學二 Quiz 題庫整理（Urban）",
        tags: ["分析化學二", "quiz", "歷屆"],
        author: "Urban",
        replies: 0,
        views: 25,
        createdAt: "2026-02-16",
        lastReplyAt: "2026-02-16 21:18",
        lastReplyBy: "Urban",
        attachments: [
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_01.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_02.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_03.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_04.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_05.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_06.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_07.pdf",
            "./assets/analytical_chem/analytical2/quiz/class21/quiz_08.pdf",
            "./assets/analytical_chem/analytical2/quiz/class22/quiz_9th_march_2021_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class22/quiz_16th_march_2021_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_1st_march_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_8th_march_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_7th_apr_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_12th_apr_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_19th_apr_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class23/quiz_26th_apr_2022_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_5th_march_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_12th_march_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_9th_april_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_16th_april_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_23rd_april_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_14th_may_2024_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class25/quiz_14th_may_2024_answers_1.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_4th_march_2025_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_11th_march_2025_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_1st_apr_2025_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_8th_april_2025_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_6th_may_2025_answers.pdf",
            "./assets/analytical_chem/analytical2/quiz/class26/quiz_13th_may_2025_answers.pdf"
        ]
    },
    {
        id: "inorganic-chem-1-solid-mid2-notes",
        status: "new",
        category: "mid2",
        department: "化學系",
        subject: "無機化學I",
        title: "【期中二】無機化學I（固態）筆記",
        tags: ["無機化學I", "固態", "筆記"],
        author: "黃暄益",
        replies: 0,
        views: 1,
        createdAt: "2026-02-17",
        lastReplyAt: "2026-02-17 01:00",
        lastReplyBy: "黃暄益",
        attachment: "./assets/inorganic_chem/mid2_note/inorganic_chem_mid2_note_photos.pdf"
    }
];
